# Generated by Django 4.2.4 on 2023-08-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='number_views',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='превью (изображение)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publication_attribute',
            field=models.BooleanField(default=True, verbose_name='признак публикации'),
        ),
    ]
